"""Tests for payload/build.py."""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from payload import aes, build  # noqa: E402


HEX_CHUNK_RE = re.compile(r'"([0-9a-fA-F]+)"')


def extract_payload_hex(bas_text: str) -> bytes:
    m = re.search(
        r"GetEncryptedShellcode.*?Dim h As String(.*?)GetEncryptedShellcode = HexToBytes",
        bas_text, re.DOTALL,
    )
    if not m:
        raise ValueError("No GetEncryptedShellcode body found")
    chunks = HEX_CHUNK_RE.findall(m.group(1))
    return bytes.fromhex("".join(chunks))


def extract_hex_call(bas_text: str, func_name: str) -> bytes:
    m = re.search(rf'{func_name}.*?HexToBytes\("([0-9a-fA-F]+)"\)', bas_text, re.DOTALL)
    if not m:
        raise ValueError(f"No {func_name} hex literal found")
    return bytes.fromhex(m.group(1))


def test_build_emits_required_functions(tmp_path):
    sc = tmp_path / "sc.bin"
    sc.write_bytes(b"\x90" * 17)
    out = tmp_path / "Payload.bas"
    assert build.main([str(sc), "--out", str(out), "--seed", "1"]) == 0
    text = out.read_text(encoding="utf-8")
    assert "AUTOGENERATED by payload/build.py" in text
    assert "GetEncryptedShellcode" in text
    assert "GetPayloadKey" in text
    assert "GetPayloadNonce" in text


def test_build_roundtrip(tmp_path):
    sc = tmp_path / "sc.bin"
    pt = bytes(range(64))
    sc.write_bytes(pt)
    out = tmp_path / "Payload.bas"
    assert build.main([str(sc), "--out", str(out), "--seed", "7"]) == 0
    text = out.read_text(encoding="utf-8")
    ct = extract_payload_hex(text)
    key = extract_hex_call(text, "GetPayloadKey")
    nonce = extract_hex_call(text, "GetPayloadNonce")
    assert len(key) == 32
    assert len(nonce) == 16
    assert aes.aes_256_ctr(ct, key, nonce) == pt


def test_build_no_aes_emits_plaintext(tmp_path):
    sc = tmp_path / "sc.bin"
    pt = b"\xde\xad\xbe\xef"
    sc.write_bytes(pt)
    out = tmp_path / "Payload.bas"
    assert build.main([str(sc), "--out", str(out), "--no-aes", "--seed", "0"]) == 0
    assert extract_payload_hex(out.read_text(encoding="utf-8")) == pt


def test_build_seed_is_deterministic(tmp_path):
    sc = tmp_path / "sc.bin"
    sc.write_bytes(b"\x00" * 32)
    out1 = tmp_path / "p1.bas"
    out2 = tmp_path / "p2.bas"
    assert build.main([str(sc), "--out", str(out1), "--seed", "99"]) == 0
    assert build.main([str(sc), "--out", str(out2), "--seed", "99"]) == 0
    t1, t2 = out1.read_text(), out2.read_text()
    assert extract_payload_hex(t1) == extract_payload_hex(t2)
    assert extract_hex_call(t1, "GetPayloadKey") == extract_hex_call(t2, "GetPayloadKey")
    assert extract_hex_call(t1, "GetPayloadNonce") == extract_hex_call(t2, "GetPayloadNonce")


def test_build_respects_explicit_key_and_nonce(tmp_path):
    sc = tmp_path / "sc.bin"
    sc.write_bytes(b"hello world!\n")
    out = tmp_path / "Payload.bas"
    key_hex = "11" * 32
    nonce_hex = "22" * 16
    assert build.main(
        [str(sc), "--out", str(out), "--key-hex", key_hex, "--nonce-hex", nonce_hex]
    ) == 0
    text = out.read_text(encoding="utf-8")
    assert extract_hex_call(text, "GetPayloadKey").hex() == key_hex
    assert extract_hex_call(text, "GetPayloadNonce").hex() == nonce_hex


def test_build_missing_shellcode_fails(tmp_path, capsys):
    out = tmp_path / "Payload.bas"
    rc = build.main([str(tmp_path / "nope.bin"), "--out", str(out)])
    assert rc == 1
    assert "not found" in capsys.readouterr().err


def test_build_empty_shellcode_fails(tmp_path, capsys):
    sc = tmp_path / "empty.bin"
    sc.write_bytes(b"")
    out = tmp_path / "Payload.bas"
    rc = build.main([str(sc), "--out", str(out)])
    assert rc == 1
    assert "empty" in capsys.readouterr().err


def test_build_validate_flag_round_trips(tmp_path, capsys):
    sc = tmp_path / "sc.bin"
    sc.write_bytes(b"validate me" * 5)
    out = tmp_path / "Payload.bas"
    rc = build.main([str(sc), "--out", str(out), "--seed", "3", "--validate"])
    assert rc == 0
    assert "round-trip OK" in capsys.readouterr().out


def test_chunk_hex_respects_chunk_length():
    chunks = build.chunk_hex(b"\x00" * 300)
    assert len(chunks) == 3
    assert "".join(chunks) == "00" * 300
    assert all(len(c) <= 200 for c in chunks)


def test_chunk_hex_empty_input():
    assert build.chunk_hex(b"") == [""]
